# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ec572d357dc5fbd8cfac17a9a21d02cedc4e7249d4637d25a89517125804e1f839effb592fb2115581d3da37ab199c2344e08d5bc08ea3057cbeaa784d05b84

test:
  secret_key_base: fd4f47238340323737e3b38c64b97158aea4fe2cdd43799a7ebc098bfabb485119141c8071d72c54017d84364b83b0330bf3ca6c8e521891fe4cbc0f676557e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
